# Generated by Django 5.0.6 on 2024-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_ordereditem_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("discount_amount", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
