# Generated by Django 5.0.6 on 2024-07-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_coupon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="code",
            new_name="coupon_code",
        ),
        migrations.RenameField(
            model_name="coupon",
            old_name="is_active",
            new_name="is_expired",
        ),
        migrations.AddField(
            model_name="coupon",
            name="minimum_amount",
            field=models.FloatField(default=500, null=True),
        ),
    ]
