# Generated by Django 5.0.6 on 2024-07-07 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_code_coupon_coupon_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
