# Generated by Django 5.0.6 on 2024-05-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('size_s', models.BooleanField(default=False)),
                ('size_m', models.BooleanField(default=False)),
                ('size_l', models.BooleanField(default=False)),
                ('size_xl', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='media')),
                ('image2', models.ImageField(upload_to='media')),
                ('image3', models.ImageField(upload_to='media')),
                ('on_hand_quantity', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
                ('delete_status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
