# Generated by Django 5.0.6 on 2024-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image1', models.ImageField(upload_to='media/')),
                ('banner_image2', models.ImageField(upload_to='media/')),
                ('banner_title1', models.CharField(max_length=100)),
                ('banner_title2', models.CharField(max_length=100)),
                ('banner_subtitle1', models.CharField(max_length=100)),
                ('banner_subtitle2', models.CharField(max_length=100)),
                ('banner_desc1', models.CharField(max_length=100)),
                ('banner_desc2', models.CharField(max_length=100)),
            ],
        ),
    ]
