# Generated by Django 5.0.6 on 2024-06-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_readblogs_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp_price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
