# Generated by Django 5.0.6 on 2024-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('jackets', 'Jackets'), ('tshirts', 'T-shirts'), ('hoodies', 'Hoodies'), ('jeans', 'Jeans'), ('pants', 'Pants')], max_length=50, null=True),
        ),
    ]
