# Generated by Django 5.0.6 on 2024-07-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_contactus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
    ]
